<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="UnitTest.mdf" />
    <None Remove="UnitTest_log.ldf" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="UnitTest.mdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="UnitTest_log.ldf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.3" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.3" />
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShahJe.Sql.Dapper.Extensions\ShahJe.Sql.Dapper.Extensions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="UnitTest.mdf" />
    <Resource Include="UnitTest_log.ldf" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="AsyncRepositoryTests.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="RepositoryTests.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

</Project>
